module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("users", [
      {
        firstName: "Soy",
        lastName: "Admin",
        userName: "SoyAdmin",
        isAdmin: true,
        email: "soyadmin@admin.com",
        password:
          "$2a$05$bL1E5YTZ7xZbKdczSCIA5ejlNm1NJnSrSPF77vvr18PBGHl.cQ1p6",
        country: "Argentina",
        city: "Buenos Aires",
        street: "avenida de Mayo",
        addressnumber: "1000",
        postcode: "1000",
        nlsuscribe: false,
        isGmail: false,
        count: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        firstName: "Ernesto",
        lastName: "Ramirez Guitierrez",
        userName: "Ernesto1234",
        isAdmin: false,
        email: "ernestoramirez@gmail.com",
        password:
          "$2a$05$bL1E5YTZ7xZbKdczSCIA5ejlNm1NJnSrSPF77vvr18PBGHl.cQ1p6",
        country: "Argentina",
        city: "Buenos Aires",
        street: "avenida de Mayo",
        addressnumber: "1000",
        postcode: "1000",
        nlsuscribe: false,
        isGmail: false,
        count: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        firstName: "Lautaro",
        lastName: "Hererra De Santos",
        userName: "LautaroHerreta44",
        isAdmin: false,
        email: "lautoraherrera@gmail.com",
        password:
          "$2a$05$bL1E5YTZ7xZbKdczSCIA5ejlNm1NJnSrSPF77vvr18PBGHl.cQ1p6",
        country: "Argentina",
        city: "Buenos Aires",
        street: "avenida de Mayo",
        addressnumber: "1000",
        postcode: "1000",
        nlsuscribe: false,
        isGmail: false,
        count: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        firstName: "Matias",
        lastName: "Stefanuti",
        userName: "matute",
        isAdmin: true,
        email: "mstefanutti@gmail.com",
        password:
          "$2a$05$bL1E5YTZ7xZbKdczSCIA5ejlNm1NJnSrSPF77vvr18PBGHl.cQ1p6",
        country: "Argentina",
        city: "Buenos Aires",
        street: "avenida de Mayo",
        addressnumber: "1000",
        postcode: "1000",
        nlsuscribe: false,
        isGmail: false,
        count: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        firstName: "Roberto",
        lastName: "Leal",
        userName: "rleal",
        isAdmin: false,
        email: "rleal@gmail.com",
        password:
          "$2a$05$bL1E5YTZ7xZbKdczSCIA5ejlNm1NJnSrSPF77vvr18PBGHl.cQ1p6",
        country: "Argentina",
        city: "Buenos Aires",
        street: "avenida de Mayo",
        addressnumber: "1000",
        postcode: "1000",
        nlsuscribe: false,
        isGmail: false,
        count: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        firstName: "Gilberto",
        lastName: "Gomez",
        userName: "ggomez",
        isAdmin: false,
        email: "ggomez@gmail.com",
        password:
          "$2a$05$mVsGEgYlAuEjUdhFwvWN2.Y.3zkThJEY8jctFQi.es8.stK0tJH8C",
        country: "Argentina",
        city: "Buenos Aires",
        street: "avenida de Mayo",
        addressnumber: "1000",
        postcode: "1000",
        nlsuscribe: false,
        isGmail: false,
        count: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("users", null, {});
  },
};
