module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("cartproduct", [
      {
        cartId: 1,
        finalproductId: 1,
        quantity: 2,
        price: 5000,
        state: "reserved",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cartId: 1,
        finalproductId: 2,
        quantity: 1,
        price: 7000,
        state: "reserved",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cartId: 1,
        finalproductId: 3,
        quantity: 1,
        price: 7000,
        state: "finished",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cartId: 2,
        finalproductId: 1,
        quantity: 1,
        price: 7000,
        state: "reserved",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cartId: 2,
        finalproductId: 3,
        quantity: 1,
        price: 7000,
        state: "finished",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cartId: 3,
        finalproductId: 1,
        quantity: 1,
        price: 5000,
        state: "reserved",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cartId: 3,
        finalproductId: 2,
        quantity: 1,
        price: 5000,
        state: "finished",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cartId: 3,
        finalproductId: 3,
        quantity: 1,
        price: 7000,
        state: "reserved",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cartId: 3,
        finalproductId: 4,
        quantity: 1,
        price: 7000,
        state: "rejected",
        createdAt: new Date(),
        updatedAt: new Date(),
      }, 
      //======================================================================================
      {
        cartId: 2,
        finalproductId: 1,
        quantity: 1,
        price: 7000,
        state: "rejected",
        createdAt: new Date(),
        updatedAt: new Date(),
      }, 
      {
        cartId: 1,
        finalproductId: 2,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-01'),
      },
      {
        cartId: 1,
        finalproductId: 6,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-02'),
      },
      {
        cartId: 2,
        finalproductId: 8,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-02'),
      },
      {
        cartId: 2,
        finalproductId: 1,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-03'),
      },
      {
        cartId: 4,
        finalproductId: 1,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-03'),
      },
      {
        cartId: 3,
        finalproductId: 2,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-03'),
      },
      {
        cartId: 3,
        finalproductId: 5,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-03'),
      },
      {
        cartId: 2,
        finalproductId: 2,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-04'),
      },
      {
        cartId: 2,
        finalproductId: 4,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-04'),
      },
      {
        cartId: 2,
        finalproductId: 6,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-04'),
      },
      {
        cartId: 3,
        finalproductId: 4,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-04'),
      },
      {
        cartId: 1,
        finalproductId: 2,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-04'),
      },
      {
        cartId: 2,
        finalproductId: 4,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-05'),
      },
      {
        cartId: 2,
        finalproductId: 1,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-05'),
      },
      {
        cartId: 2,
        finalproductId: 7,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-05'),
      },
      {
        cartId: 1,
        finalproductId: 1,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-07'),
      },
      {
        cartId: 2,
        finalproductId: 8,
        quantity: 1,
        price: 7000,
        state: "paid",
        createdAt: new Date(),
        updatedAt: new Date('2021-04-07'),
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("cartproduct", null, {});
  },
};
